version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "actions"
      - "dependencies"
    reviewers:
      - "karl-d"
      - "nandogameiro"
