name: 'Test CI'
on:
  workflow_dispatch:
  pull_request:

jobs:
  composer:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, bcmath, curl, libxml, gettext, exif, iconv, intl, mbstring, gd, imagick, soap, sockets, zip, pcntl, pdo, mysql, pdo_mysql
          coverage: pcov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Composer Install
        run: composer install
      - name: Tar files # to keep right permissions
        run: tar -cvf vendor.tar vendor
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: composer
          path: vendor.tar


  lint:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: composer
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, bcmath, curl, libxml, gettext, exif, iconv, intl, mbstring, gd, imagick, soap, sockets, zip, pcntl, pdo, mysql, pdo_mysql
          coverage: pcov
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: composer
          path: vendor.tar
      - name: UnTar files # to keep right permissions
        run: tar -xvf vendor.tar vendor
      - name: PHP Coding Standards
        run: composer pint

  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: composer
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, bcmath, curl, libxml, gettext, exif, iconv, intl, mbstring, gd, imagick, soap, sockets, zip, pcntl, pdo, mysql, pdo_mysql
          coverage: pcov
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: composer
          path: vendor.tar
      - name: UnTar files # to keep right permissions
        run: tar -xvf vendor.tar vendor
      - name: PHP Coding Standards
        run: composer test
